version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8060:8000
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://postgres:RJUhYYCAyYcF30sV1SxiqP3v8VNQHNpVdBBhCpKZl9DQOxog0YK9zk6ZTZyRx5iz@49.13.234.182:5432/postgres"
    command: ./entrypoint.sh
    depends_on:
      db:
        condition: service_healthy

volumes:
  horilla-data:
