version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:8000
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://postgres:N2paAMIlkujzg9UN75xVi57wMzDd2ZPUPd26K8hWNBl20jiynNmaGtXU3wSfcRhi@ogcw8sw8c0kkkgc4ss0kskkg:5432/postgres"
    command: ./entrypoint.sh
    volumes:
      - ./horilla:/app/horilla
